# Generated by Django 4.2.6 on 2023-12-07 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ZohoModuleRecord",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, verbose_name="Id записи"
                    ),
                ),
                (
                    "module_name",
                    models.CharField(max_length=100, verbose_name="Наименование модуля"),
                ),
                (
                    "record_name",
                    models.CharField(max_length=100, verbose_name="Наименование записи"),
                ),
                (
                    "accessed_at",
                    models.DateField(auto_now=True, verbose_name="Последняя дата доступа"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ZohoImage",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, verbose_name="Id картинки"
                    ),
                ),
                ("image", models.ImageField(upload_to="", verbose_name="Адресс картинки")),
                (
                    "zoho_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.zohomodulerecord",
                        verbose_name="Зохо запись",
                    ),
                ),
            ],
        ),
    ]
