# Generated by Django 4.2.10 on 2024-02-07 14:39

from django.db import migrations, models
import fillers.models


class Migration(migrations.Migration):
    dependencies = [
        ("fillers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverydatamodel",
            name="main_image",
            field=models.ImageField(
                null=True,
                upload_to=fillers.models.user_directory_path,
                verbose_name="Первая большая картинка",
            ),
        ),
    ]
