# Generated by Django 4.2.10 on 2024-02-07 16:14

from django.db import migrations, models
import fillers.models


class Migration(migrations.Migration):
    dependencies = [
        ("fillers", "0002_deliverydatamodel_main_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactsDataModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        null=True,
                        upload_to=fillers.models.user_directory_path,
                        verbose_name="Первая большая картинка",
                    ),
                ),
            ],
        ),
    ]
