# Generated by Django 4.2.6 on 2023-12-07 07:29

from django.db import migrations, models

import mainpage.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "international_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Телефонный номер 1 международного оператора",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=15, verbose_name="Название")),
                ("link", models.URLField(verbose_name="Полный адресс ссылки")),
                (
                    "ordinal_number",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4")], unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MainSlider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "description_up",
                    models.CharField(max_length=255, verbose_name="Подпись верхняя"),
                ),
                (
                    "description_down",
                    models.CharField(max_length=255, verbose_name="Подпись нижняя"),
                ),
                (
                    "picture",
                    models.ImageField(
                        null=True,
                        upload_to=mainpage.models.user_directory_path,
                        verbose_name="Картинка",
                    ),
                ),
                ("button", models.CharField(max_length=50, verbose_name="Подпись кнопки")),
                (
                    "link",
                    models.CharField(
                        blank=True, default="", max_length=15, verbose_name="Ссылка кнопки"
                    ),
                ),
                (
                    "ordinal_number",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4")], unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeoBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("description", models.CharField(max_length=255, verbose_name="Подпись")),
                (
                    "picture",
                    models.ImageField(
                        null=True,
                        upload_to=mainpage.models.user_directory_path,
                        verbose_name="Картинка",
                    ),
                ),
                ("button", models.CharField(max_length=50, verbose_name="Подпись кнопки")),
                ("link", models.CharField(max_length=255, verbose_name="Ссылка")),
            ],
        ),
    ]
