# Generated by Django 4.2.6 on 2023-12-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ZohoOAuth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "client_id",
                    models.CharField(
                        blank=True, max_length=60, null=True, verbose_name="Client id"
                    ),
                ),
                (
                    "client_secret",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Client secret"
                    ),
                ),
                (
                    "grant_token",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Grant token"
                    ),
                ),
                (
                    "refresh_token",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Refresh token"
                    ),
                ),
                (
                    "redirect_url",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Redirect url"
                    ),
                ),
                (
                    "access_token",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Access token"
                    ),
                ),
                (
                    "token_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Token id"
                    ),
                ),
                ("expires_in", models.BigIntegerField(verbose_name="Time expire")),
                ("user_email", models.EmailField(max_length=254, verbose_name="User email")),
            ],
            options={
                "verbose_name": "Zoho OAuth token",
            },
        ),
    ]
